### PR TITLE
for safety

### PR DESCRIPTION
**Pull request by nedlig**
Played around with it more:
added SVG icon. Search icon -> coffee mug
changed the search bar to an animated search bar (experiment)

made separate styled.js for more organized, cleaner code.

I don't know if we should use font-awesome icon? 
What do you guys use for icons? Some of the nice-looking ones aren't free. 

Let me know if you guys see any errors on your console. My console is clean.

### CODE REVIEW

**Comment by soonbinan** [comment]
Screen Shot 2020-05-08 at 01 59 13
I don't know why I'm getting these. What should I do with these untracked files?

**Comment by greeendiamond** [comment]
https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

@soonbinan 

Remove ds_store files..

**Comment by greeendiamond** [comment]
font-awesome is one of the icon services that are used generally since it's free and easy to use.

**Comment by greeendiamond** [comment]
와 씨.. 잘 했다 이건.
svg 잘 했고. 애니메이션도 이쁘네.
특히 file refactoring 한거. 
와.. 이건 진짜 붓캠 다녀온 애들보다 100배 낫다. 

@soonbinan 
@kimhk812 

난 합격일세.

**Pull request merged**
